# Generated by Django 4.2.3 on 2023-07-14 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_model_rocket_edition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rocket',
            name='status',
            field=models.CharField(choices=[('development', 'Development'), ('integration', 'Integration'), ('testing', 'Testing'), ('ready', 'Ready'), ('maintainance', 'Maintainance')], max_length=255),
        ),
    ]
