# Generated by Django 4.2.3 on 2023-07-14 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_rocket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launch',
            name='status',
            field=models.CharField(choices=[('launched', 'Launched'), ('postponed', 'Postponed'), ('ready', 'Ready'), ('failed', 'Failed')], max_length=255),
        ),
    ]
