# Generated by Django 4.2.3 on 2023-07-14 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_launch_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rocket',
            old_name='status',
            new_name='stage',
        ),
    ]
