# Generated by Django 4.2.3 on 2023-07-14 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_launch_reentry_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payload',
            name='launch',
        ),
        migrations.AddField(
            model_name='payload',
            name='rocket',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.rocket'),
            preserve_default=False,
        ),
    ]
